version: '2'
services:
  web:
    image: odoo: <odoo_version>
    depends_on:
      - db
    ports:
      - "<ports_web>:8069"
    tty: true
    # command: -- --dev all
    command: -u nama_module -d nama_database
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
  db:
    image: postgres: <postgres_version>
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "<ports_db>:5432"
volumes:
  odoo-web-data:
  odoo-db-data:
