version: '2'
services:
  web:
    image: odoo:____
    depends_on:
      - db
    ports:
      - "____:8069"
    tty: true
    command: -- --dev all
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
  db:
    image: postgres:____
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "____:5432"
volumes:
  odoo-web-data:
  odoo-db-data:
